application: qmagicformula
version: 1
runtime: python27
api_version: 1
threadsafe: no

inbound_services:
- warmup

handlers:
- url: /tasks/updatestockinfo
  script: update_stock_info.py
  login: admin

- url: /tasks/update.*marketcapital
  script: update_stock_info.py
  login: admin

- url: /tasks/updateearnings
  script: update_stock_info.py
  login: admin

- url: /tasks/.*formula
  script: show_stock_info.py
  login: admin
  
- url: /tasks/netcurrentassetapproach
  script: show_stock_info.py
  login: admin
  
- url: /netcurrentassetapproach
  script: show_stock_info.py
  
- url: /.*formula
  script: show_stock_info.py
  
- url: /postman
  script: postoffice.py
  login: admin
  
- url: /client
  script: postoffice.py
  login: admin
  
- url: /tasks/updategdp
  script: gdp.py
  login: admin
  
- url: /tasks/showstockindex
  script: stock_index.py
  login: admin
  
- url: /tasks/update.*categoryinfo
  script: update_category_info.py
  login: admin
  
- url: /tasks/postoffice
  script: postoffice.py
  login: admin
  
- url: /tasks/mail
  script: postoffice.py
  login: admin
  
- url: /
  static_dir: static
  login: admin
