application: qmagicformula
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /tasks/updatestockinfo
  script: update_stock_info.py
#  login: admin

- url: /tasks/updateallmarketcapital
  script: update_stock_info.py
#  login: admin

- url: /tasks/updatesinglemarketcapital
  script: update_stock_info.py
#  login: admin

- url: /tasks/updateearnings
  script: update_stock_info.py
#  login: admin

- url: /tasks/updateexchangerate
  script: exchange_rate.py
  
- url: /tasks/showstockinfo
  script: show_stock_info.py